name: onlineenrollment
description: "Online Enrollment System"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0

  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0  


  http: ^1.1.0
  http_parser: ^4.0.0
  


  dio: ^5.9.2  
  
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  
  image_picker: ^1.0.4
  provider: ^6.1.1
  intl: ^0.18.1
  
  screens: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/1973802.webp